# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
    or
    
**in command prompt type:**
    pip install numpy
    
**In google colab it is already available you can directly use**     
**for more info on installation, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

For example, you can create an array from a regular Python list or tuple using the `array` function.






**`syntax: np.array(object, dtype=None,ndmin=0)`**

#### Create an Array from List

In [16]:
# Create an 1d -array from python list
List1 = [2,6,3,4]

array = np.array(List1)

In [17]:
array

array([2, 6, 3, 4])

In [5]:
#create a matrix with 2-rows and 3-columns
List2 = [[2,3,6],[5,4,8]]

In [9]:
# Create an array from above matrix

array = np.array(List2)
array

array([[2, 3, 6],
       [5, 4, 8]])

#### Create an array from tuple

In [10]:
# tuple
Tuple = (2,3,6,9)

array = np.array(Tuple)

In [11]:
array

array([2, 3, 6, 9])

#### Array of integers, floats and complex Numbers

In [39]:
A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [40]:
A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)


[[1.1 2.  3. ]
 [3.  4.  5. ]]


In [41]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

**syntax**

   **`np.arange([start,] stop[, step,], dtype=None)`**

Return evenly spaced values within a given interval.

In [36]:
array = np.arange(0,10) # create an array from 0 to 10 (10 is exclusive)

In [37]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
array = np.arange(0,10,2)

In [43]:
array

array([0, 2, 4, 6, 8])

### zeros

Return a new array of given shape and type, filled with zeros.

**Syntax**

 **`np.zeros(shape, dtype=float, order='C')`**
   
- Shape of the new array, e.g., `(7, 3)` or `5`
- The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`

In [45]:
# Generate an array of zeros of shape 3
Zeros = np.zeros(4)
Zeros

array([0., 0., 0., 0.])

In [46]:
Zeros = np.zeros((4,5))
Zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Generate an array of Zeros of shape 5x5


In [ ]:
# Generate an array of ones of shape 3


In [ ]:
# Generate an array of ones of shape of 5X5


### linspace
Return evenly spaced numbers over a specified interval.

**syntax**

**`np.linspace(start, stop, num=50,dtype=None)`**



In [47]:
# Generate an array between 2 to 5
L = np.linspace(0,10)
L

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [48]:
# Generate an array 100 elements between 2 to 5
L = np.linspace(2,5,100)
L

array([2.        , 2.03030303, 2.06060606, 2.09090909, 2.12121212,
       2.15151515, 2.18181818, 2.21212121, 2.24242424, 2.27272727,
       2.3030303 , 2.33333333, 2.36363636, 2.39393939, 2.42424242,
       2.45454545, 2.48484848, 2.51515152, 2.54545455, 2.57575758,
       2.60606061, 2.63636364, 2.66666667, 2.6969697 , 2.72727273,
       2.75757576, 2.78787879, 2.81818182, 2.84848485, 2.87878788,
       2.90909091, 2.93939394, 2.96969697, 3.        , 3.03030303,
       3.06060606, 3.09090909, 3.12121212, 3.15151515, 3.18181818,
       3.21212121, 3.24242424, 3.27272727, 3.3030303 , 3.33333333,
       3.36363636, 3.39393939, 3.42424242, 3.45454545, 3.48484848,
       3.51515152, 3.54545455, 3.57575758, 3.60606061, 3.63636364,
       3.66666667, 3.6969697 , 3.72727273, 3.75757576, 3.78787879,
       3.81818182, 3.84848485, 3.87878788, 3.90909091, 3.93939394,
       3.96969697, 4.        , 4.03030303, 4.06060606, 4.09090909,
       4.12121212, 4.15151515, 4.18181818, 4.21212121, 4.24242

## eye

   
Creates an identity matrix

**syntax**

**`np.eye(N, M=None,dtype=<class 'float'>)`**
   
- N : int
  Number of rows in the output.
- M : int, optional
  Number of columns in the output. If None, defaults to `N`.
- dtype : data-type, optional
  Data-type of the returned array.


In [50]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [51]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## ones

Returns an array of all ones.

**`np.ones(shape, dtype=None, order='C')`**

In [2]:
a = np.ones((2,2))

In [3]:
a

array([[1., 1.],
       [1., 1.]])

## constant array
Return a new array of given shape and type, filled with `fill_value`.

**`np.full(shape, fill_value, dtype=None, order='C')`**

In [5]:
#Create a 3x3 array with constant value 7

np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

## Random 

Numpy also has lots of ways to create random number arrays:

### 1. rand

Random values in a given shape.

Create an array of the given shape and populate it with
random samples from a **uniform distribution**
over ``[0, 1)``.

**syntax**

   `rand(d0, d1, ..., dn)`
   
   - d0, d1, ..., dn : int, optional
    The dimensions of the returned array, should all be positive.


In [52]:
# Generate an array of 5 random numbers from a uniform distribution
U = np.random.rand(5)
U

array([0.93108013, 0.60004158, 0.5464251 , 0.53030544, 0.12088351])

In [53]:
# Generate an array of 5,2 random numbers from a uniform distribution

U = np.random.rand(5,2)
U

array([[0.126237  , 0.64762973],
       [0.68357311, 0.0343868 ],
       [0.56585126, 0.30508979],
       [0.1710573 , 0.6473295 ],
       [0.81710764, 0.34481651]])

### 2.randn

Return a sample (or samples) from the **standard normal distribution**.

**syntax**
  
  `randn(d0, d1, ..., dn)`

In [55]:
# Generate an array of 5 random numbers from a standard normal distribution

N = np.random.randn(5)
N

array([-0.17965169,  0.11201414, -0.52285474, -0.98552652, -1.75540279])

In [61]:
# Generate an array of 5,2 random numbers from a standard normal distribution

N = np.random.randn(5,2)
N

array([[ 0.64424681, -0.06518531],
       [-0.81488252, -0.11388976],
       [-0.86050117,  0.18817889],
       [ 1.17206601,  0.66668372],
       [-0.41997441,  0.23690025]])

### 3. randint
Return random integers from `low` (inclusive) to `high` (exclusive).

**syntax**

`randint(low, high=None, size=None)`


In [1]:
import numpy as np

In [36]:
np.random.randint(0,10,size = (2,2))

array([[3, 9],
       [6, 1]])

## Array Attributes


Let's discuss some useful attributes of an array like the size, shape, memory consumption, and data types.

### 1. ndarray.shape 

This array attribute returns a tuple consisting of `array dimensions`. It can also be used to resize the array.

In [47]:
arr1 = np.array([[3,4],[8,9]])
arr2 = np.array([[3,4,5],[9,7,8]])
arr3 = np.array([[3,6,8,7],[5,9,8,7],[2,5,3,7]])

In [48]:
arr1.shape

(2, 2)

In [49]:
arr2.shape

(2, 3)

In [50]:
arr3.shape

(3, 4)

In [51]:
#Resize arr3 by using shape attribute
arr3.shape = (4,3)

In [52]:
arr3

array([[3, 6, 8],
       [7, 5, 9],
       [8, 7, 2],
       [5, 3, 7]])

## 2. Reshape( )
Returns an array containing the same data with a new shape.

In [53]:
arr4 = np.arange(0,10).reshape(2,5)

In [54]:
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 3. ndarray.ndim

This array attribute returns the `number of array dimensions`.

In [57]:
# One dimensional array

onedm = np.array([2,3,6,9])
onedm.ndim

1

In [60]:
# Two dimensional array
twodm = np.array([[2,5,8],[7,8,9]])

In [62]:
twodm.ndim

2

In [63]:
# Three dimensional array
threedm = np.array([[[2,3,6],[5,8,9],[9,8,7]]])

In [64]:
threedm.ndim

3

## 4.ndarray.itemsize

This array attribute returns the length of each element of array in bytes.

In [65]:
onedm.itemsize

4

In [66]:
threedm.itemsize

4

## 5.ndarray.size

Returns the total size of the array

In [67]:
onedm.size

4

In [68]:
twodm.size

6

In [69]:
threedm.size

9

## 6.ndarray.dtype

Returns the type of data


In [70]:
onedm.dtype

dtype('int32')

In [74]:
onedm.astype(float)

array([2., 3., 6., 9.])

## 7. ndarray.astype()
a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

Copy of the array, cast to a specified type.

In [76]:
onedm.astype(float)

array([2., 3., 6., 9.])