# Indexing : Accessing Single Elements


Python’s standard list indexing, indexing in NumPy will feel
quite familiar.

##  one-dimensional array
You can access the ith value (counting from
zero) by specifying the desired index in square brackets, just as with Python lists:

> **`syntax : array[index]`**-- **for single item**

##### Fancy Indexing
It means passing an array of indices to access multiple array elements at once.

> **`syntax : array[[index,index..]]`** -- **for multiple items based on index**

In [1]:
import numpy as np

In [2]:
arr = np.array([2,3,6,7,8,9,1])

In [6]:
arr[2] # value at index 2

6

In [7]:
arr[[2,5,4]] # To access multiple elements send a list of index numbers


array([6, 9, 8])

In [9]:
arr[[2,1,5,6]]

array([6, 3, 9, 1])

## Multi-dimensional array

In a multidimensional array, you access items using a comma-separated tuple of
indices:

**`syntax : array[row ,column]`**

In [10]:
arr2 = np.arange(10)

In [11]:
arr2 = arr2.reshape(2,5)

In [12]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
arr2[0][0]

0

In [15]:
arr2[0,0]

0

In [16]:
arr2[0][1]

1

In [17]:
arr2[0,1]

1

In [17]:
arr2[0,1]

1

In [18]:
arr2[1,2]

7

In [19]:
arr2[1,4]

9

In [18]:
arr3 =  np.arange(9)

In [19]:
arr3 = arr3.reshape((3,3))

In [20]:
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
arr3[2,2]

8

In [27]:
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr3[1,2]

5

In [29]:
arr3[2,1]

7

#### 3D -Indexing


In [21]:
l  = [[[2, 3, 6, 7], [4, 7, 8, 9], [7, 8, 9, 6]]]

In [22]:
arr_3d = np.array(l)

In [23]:
arr_3d

array([[[2, 3, 6, 7],
        [4, 7, 8, 9],
        [7, 8, 9, 6]]])

In [24]:
arr_3d[0]

array([[2, 3, 6, 7],
       [4, 7, 8, 9],
       [7, 8, 9, 6]])

In [25]:
arr_3d[0][0]

array([2, 3, 6, 7])

In [26]:
arr_3d[0][0][0]

2

In [27]:
arr_3d[0][1][0]

4

In [28]:
arr_3d[0,1:3,1:3]

array([[7, 8],
       [8, 9]])

# Slicing : Accessing sub-arrays

Access subarrays with the slice notation, marked by the colon (:) character.

To access a slice of an array x, use this: **`x[start:stop:step]`**

## one dimensional subarrays 

In [30]:
x = np.array([5,7,8,9,3,5,1])

In [31]:
x

array([5, 7, 8, 9, 3, 5, 1])

In [32]:
# All elements
x[:]

array([5, 7, 8, 9, 3, 5, 1])

In [33]:
# first five elements
x[:5]

array([5, 7, 8, 9, 3])

In [34]:
# elements after 2nd index
x[2:]

array([8, 9, 3, 5, 1])

In [35]:
# sub-array from 2 to 5(exclusive)
x[2:5]

array([8, 9, 3])

In [37]:
x

array([5, 7, 8, 9, 3, 5, 1])

In [36]:
# every 2nd or other element
x[ : : 2]

array([5, 8, 3, 1])

In [38]:
# every other element starting from 1
x[ 1: : 2]

array([7, 9, 5])

## Multidimensional sub-arrays

Multidimensional slices work in the same way, with multiple slices separated by commas.

**`x[ row_start:row_end:step  , col_start :col_end:step]`**

In [39]:
x = np.random.rand(3,3)

In [40]:
x

array([[0.85834242, 0.84787551, 0.77797098],
       [0.53090327, 0.72204142, 0.49028601],
       [0.42345489, 0.25479597, 0.62413327]])

In [41]:
x[2 : ,   ]

array([[0.42345489, 0.25479597, 0.62413327]])

In [42]:
x[1:]

array([[0.53090327, 0.72204142, 0.49028601],
       [0.42345489, 0.25479597, 0.62413327]])

In [43]:
x[0: ]

array([[0.85834242, 0.84787551, 0.77797098],
       [0.53090327, 0.72204142, 0.49028601],
       [0.42345489, 0.25479597, 0.62413327]])

In [45]:
x[:,0:]

array([[0.85834242, 0.84787551, 0.77797098],
       [0.53090327, 0.72204142, 0.49028601],
       [0.42345489, 0.25479597, 0.62413327]])

In [46]:
x[ :, 0:2]

array([[0.85834242, 0.84787551],
       [0.53090327, 0.72204142],
       [0.42345489, 0.25479597]])

In [47]:
x[ : ,  0:1 ]

array([[0.85834242],
       [0.53090327],
       [0.42345489]])

In [48]:
x[ 1: , 1: ]

array([[0.72204142, 0.49028601],
       [0.25479597, 0.62413327]])

In [49]:
x[ 1:]

array([[0.53090327, 0.72204142, 0.49028601],
       [0.42345489, 0.25479597, 0.62413327]])

In [50]:
x[ 1:, :2]

array([[0.53090327, 0.72204142],
       [0.42345489, 0.25479597]])

In [51]:
x[ 1:,2:]

array([[0.49028601],
       [0.62413327]])

In [54]:
x

array([[0.85834242, 0.84787551, 0.77797098],
       [0.53090327, 0.72204142, 0.49028601],
       [0.42345489, 0.25479597, 0.62413327]])

In [55]:
x[ 2:,2:]

array([[0.62413327]])

In [61]:
x[2:,1:3]

array([[0.25479597, 0.62413327]])

In [62]:
x[2:, : 1]

array([[0.42345489]])

In [63]:
x[ : 2]

array([[0.85834242, 0.84787551, 0.77797098],
       [0.53090327, 0.72204142, 0.49028601]])

In [65]:
x[ 1:2 , 1:2]

array([[0.72204142]])

In [64]:
x

array([[0.85834242, 0.84787551, 0.77797098],
       [0.53090327, 0.72204142, 0.49028601],
       [0.42345489, 0.25479597, 0.62413327]])

In [66]:
x[1:2,2:3]

array([[0.49028601]])

In [68]:
x[ ::2,::2 ]

array([[0.85834242, 0.77797098],
       [0.42345489, 0.62413327]])

In [ ]:
x[ ::1, ::1]

In [ ]:
x[ : ]

In [ ]:
x[ 2:3 ]

In [ ]:
x[ 2:3, 1:2 ]